export const SKILL_OPTIONS = [
  "TypeScript",
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "C",
  "C#",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "React",
  "Next.js",
  "Node.js",
  "Express",
  "Django",
  "Flask",
  "Spring Boot",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Prisma",
  "GraphQL",
  "REST APIs",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "Docker",
  "Kubernetes",
  "AWS",
  "GCP",
  "Azure",
  "Linux",
  "Git",
  "CI/CD",
  "Machine Learning",
  "Deep Learning",
  "PyTorch",
  "TensorFlow",
  "Data Analysis",
  "Pandas",
  "SQL",
  "Cybersecurity",
  "Network Security",
  "Penetration Testing",
  "Cryptography",
  "Mobile Development",
  "iOS",
  "Android",
  "UI/UX Design",
  "Figma",
  "Product Management",
  "System Design",
  "Algorithms",
  "Testing",
  "Agile",
] as const;

export const INTEREST_OPTIONS = [
  "Software Engineering",
  "Cybersecurity",
  "Artificial Intelligence",
  "Machine Learning",
  "Fintech",
  "Healthtech",
  "Edtech",
  "Climate Tech",
  "Startups",
  "Open Source",
  "Web Development",
  "Mobile Apps",
  "Game Development",
  "Hardware",
  "Robotics",
  "Data Science",
  "Cloud Computing",
  "DevOps",
  "Product Design",
  "Human-Computer Interaction",
  "Blockchain",
  "Quantum Computing",
  "Research",
  "Hackathons",
  "Competitive Programming",
  "Entrepreneurship",
] as const;

export const OTHER_OPTION = "Other";
export const MAX_EXPERTISE_TAGS = 20;
export const MAX_TAG_LENGTH = 40;

export function parseExpertiseList(raw: string): string[] {
  return [
    ...new Set(
      raw
        .split(",")
        .map((item) => item.trim())
        .filter(Boolean)
        .map((item) => item.slice(0, MAX_TAG_LENGTH)),
    ),
  ].slice(0, MAX_EXPERTISE_TAGS);
}
