ALTER TABLE "ForumThread" ADD COLUMN IF NOT EXISTS "score" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ForumThread" ADD COLUMN IF NOT EXISTS "lastPostId" TEXT;

ALTER TABLE "ForumPost" ADD COLUMN IF NOT EXISTS "parentId" TEXT;

CREATE INDEX IF NOT EXISTS "ForumPost_parentId_idx" ON "ForumPost"("parentId");

ALTER TABLE "ForumPost" DROP CONSTRAINT IF EXISTS "ForumPost_parentId_fkey";
ALTER TABLE "ForumPost" ADD CONSTRAINT "ForumPost_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "ForumPost"("id") ON DELETE SET NULL ON UPDATE CASCADE;
