ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PROJECT_UPDATE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PROJECT_SIGNED';

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastDigestAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastMarketingAt" TIMESTAMP(3);
